<i>École Polytechnique de Montréal</i>
<br>
<i>Cours MTH2210 : Calcul scientifique pour ingénieurs</i>
<br>
<i>Session d'hiver 2023</i>

<h1><center>Installation et test des fonctions de la bibliothèque numérique du cours</center></h1>

| N'DRI Donatien    | BOUCHET Pierre-Yves |
|-------------------|---------------------|
| Matricule 9999999 | Matricule 0000000   |

# Installation ou mise à jour du module

La cellule suivante n'est à exécuter que pour installer / mettre à jour la bibliothèque numérique du cours. Le reste du temps, elle peut rester commentée.

In [ ]:
# Installation du module. Le chemin d'accès est à adapter pour chaque utilisateur.
# Il correspond au chemin pointant exactement sur l'archive téléchargée sur GitHub.
# Sur le cas d'exemple, j'ai sauvegardé l'archive dans le dossier /home/pierre-yves/Documents/MTH2210,
# puis je l'ai dézippée, puis j'ai renommé le dossier dézippé en "MTH2210.py".

%pip install -e your/path/to/the/unzipped/folder
# %pip install -e /home/pierre-yves/Documents/MTH2210/MTH2210.py

# Test du module

Chaque fonction est illustrée dans une cellule dédiée, que vous pouvez lancer indépendemment des autres.

In [1]:
# Réinitialisation complète de l'environnement
# %reset -f

# Import de la bibliothèque numérique du cours
import MTH2210

# Import des bibliothèques nécessaires intégrées à Python
import sys
import numpy as np
import matplotlib.pyplot as plt

# # Définition d'un code permettant d'alléger le visuel du notebook; issu de
# # https://stackoverflow.com/questions/27934885/how-to-hide-code-from-cells-in-ipython-notebook-visualized-with-nbviewer
# from IPython.display import HTML
# HTML('''<script>
# code_show=false; 
# function code_toggle() {
#  if (code_show){
#  $('div.input').hide();
#  } else {
#  $('div.input').show();
#  }
#  code_show = !code_show
# } 
# $( document ).ready(code_toggle);
# </script>
# Pour cacher/révéler le code brut et n'afficher que les commentaires et les résultats, cliquez <a href="javascript:code_toggle()">ici</a>.''')

## Méthode de la bissection

In [2]:
help("MTH2210.euler")

Help on function euler in MTH2210:

MTH2210.euler = euler(f, x0, t0, tm, m, output='')
    Méthode de résolution numérique d'une équation (dx/dt)(t) = f(x(t),t) par le schéma d'Euler :
        - x_0 donné, t_0 donné, pas de temps h donné,
        - x_kp1 = x_k + h*f(x_k,t_k),
        - t_kp1 = t_k + h.

    Les arguments attendus sont :
        - une fonction f, admettant en entrée un vecteur x et un réel t, renvoyant un vecteur f(x,t),
        - un vecteur  x0, condition initiale de l'équation,
        - deux réels  t0 et tm, les bornes de l'intervalle de temps sur lequel l'équation est appliquée,
        - un entier    m, le pas de discrétisation de [t0,tm], définissant donc h = (tm-t0)/m.

    L'argument optionnel est une chaîne de caractères output (défaut = "") qui renvoie les affichages de la fonction vers :
        - la sortie standard si output = "pipe",
        - un fichier ayant output comme nom+extension (le paramètre doit donc contenir l'extension voulue, et le chemin d'acc

In [3]:
MTH2210.euler()

TypeError: euler() missing 5 required positional arguments: 'f', 'x0', 't0', 'tm', and 'm'

In [4]:
def f(x):
    return(x)
(x0, x1) = (-0.5, 1/3)

xout, fout = MTH2210.bissection(f, x0, x1, output="pipe")
# xout, fout = MTH2210.bissection(f, x0, x1)

print("x =", xout)
print("f =", fout)

   k ||     x_g     |     x_d     ||     f_g     |     f_d     ||     x_c     |     f_c    
-------------------------------------------------------------------------------------------
   0 || -5.0000e-01 | +3.3333e-01 || -5.0000e-01 | +3.3333e-01 || -8.3333e-02 | -8.3333e-02
   1 || -8.3333e-02 | +3.3333e-01 || -8.3333e-02 | +3.3333e-01 || +1.2500e-01 | +1.2500e-01
   2 || -8.3333e-02 | +1.2500e-01 || -8.3333e-02 | +1.2500e-01 || +2.0833e-02 | +2.0833e-02
   3 || -8.3333e-02 | +2.0833e-02 || -8.3333e-02 | +2.0833e-02 || -3.1250e-02 | -3.1250e-02
   4 || -3.1250e-02 | +2.0833e-02 || -3.1250e-02 | +2.0833e-02 || -5.2083e-03 | -5.2083e-03
   5 || -5.2083e-03 | +2.0833e-02 || -5.2083e-03 | +2.0833e-02 || +7.8125e-03 | +7.8125e-03
   6 || -5.2083e-03 | +7.8125e-03 || -5.2083e-03 | +7.8125e-03 || +1.3021e-03 | +1.3021e-03
   7 || -5.2083e-03 | +1.3021e-03 || -5.2083e-03 | +1.3021e-03 || -1.9531e-03 | -1.9531e-03
   8 || -1.9531e-03 | +1.3021e-03 || -1.9531e-03 | +1.3021e-03 || -3.2552e-04 | 

## Méthode de la sécante

In [ ]:
help("MTH2210.secante")

In [ ]:
def f(x):
    return(x**2)
(x0,x1) = (2, 1)

xout, fout, dout = MTH2210.secante(f, x0, x1, output="pipe")
# xout, fout, dout = MTH2210.secante(f, x0, x1)

print("x =", xout)
print("f =", fout)
print("d =", dout)

## Méthode de Newton 1D

In [ ]:
help("MTH2210.newton_1d")

def f(x):
    return(np.sin(x))
def df(x):
    return(np.cos(x))
x0 = 1

xout, fout, dout = MTH2210.newton_1d(f, df, x0, output="pipe")
# xout, fout, dout = MTH2210.newton_1d(f, df, x0)

print("x =", xout)
print("f =", fout)
print("d =", dout)

## Méthode de Newton nD sans dérivées

In [ ]:
help("MTH2210.newton_nd")

In [ ]:
def f(x):
    return(x**2)
x0 = np.array([1,1,1])

xout, fout, dout = MTH2210.newton_nd(f, x0, output="pipe")
# xout, fout, dout = MTH2210.newton_nd(f, x0)

print("x =", xout)
print("f =", fout)
print("d =", dout)

## Méthode de Newton nD avec dérivées

In [ ]:
help("MTH2210.newton_nd_avec_der")

In [ ]:
def f(x):
    return(x**2)
def jac(x):
    return(2*np.diag(x))
x0 = np.array([1,1,1])

xout, fout, dout = MTH2210.newton_nd_avec_der(f, jac, x0, output="pipe")
# xout, fout, dout = MTH2210.newton_nd_avec_der(f, jac, x0)

print("x =", xout)
print("f =", fout)
print("d =", dout)

## Recherche de point fixe

In [ ]:
help("MTH2210.point_fixe")

En dimension 1 :

In [ ]:
def f(x):
    return(x**2)
x0 = 0.5

xout = MTH2210.point_fixe(f, x0, output="pipe")
# xout = MTH2210.point_fixe(f, x0)

print("x =", xout)

En dimension n > 1 :

In [ ]:
def f(x):
    return(x**2)
x0 = np.array([0.1,0.1])

xout = MTH2210.point_fixe(f, x0, output="pipe")
# xout = MTH2210.point_fixe(f, x0)

print("x =", xout)

## Interpolation de Lagrange

In [ ]:
help("MTH2210.lagrange")

In [ ]:
xe = [-1,0,1]
ye = [0,-1,0]
x  = [-2,-1,-0.5,0,0.5,1,2]

y, l = MTH2210.lagrange(xe, ye, x, output="pipe")
# y, l = MTH2210.lagrange(xe, ye, x)

print("y =", y)
print("l(5) =", l(5))
print("l(np.array([5,10,100])) =", l(np.array([5,10,100])))

## Interpolation par splines cubiques

In [ ]:
help("MTH2210.spline_cub")

Cas des splines naturelles :

In [ ]:
xe = [-1,0,1]
ye = [0,-1,0]
x  = [-2,-1,-0.5,0,0.5,1,2]

y, s = MTH2210.spline_cub(xe, ye, x, output="pipe")
# y, s = MTH2210.spline_cub(xe, ye, x)

print("y =", y)
print("s(5) =", s(5))
print("s(np.array([5,10,100])) =", s(np.array([5,10,100])))

Cas des autres splines : les conditions à gauche et à droite se définissent via des paramètres optionnels.
Ici, on ne spécifie que les conditions à gauche, donc il est sous-entendu qu'on demande les conditions naturelles à droite.

In [ ]:
xe = [-1,0,1]
ye = [0,-1,0]
x  = [-2,-1,-0.5,0,0.5,1,2]
cond_g = 1
val_g  = 0.5

y, s = MTH2210.spline_cub(xe, ye, x, cond_g, val_g, output="pipe")
# y, s = MTH2210.spline_cub(xe, ye, x, cond_g, val_g)

print("y =", y)
print("s(5) =", s(5))
print("s(np.array([5,10,100])) =", s(np.array([5,10,100])))

## Méthode d'approximation d'Euler

In [ ]:
help("MTH2210.euler")

En dimension 1 :

In [ ]:
def f(x,t):
    return(np.cos(t))
x0 = 0
(t0,tm) = (0, 2*np.pi)
m = 10

xout, tout = MTH2210.euler(lambda x,t : np.cos(t), x0, t0, tm, m, output="pipe")
# xout, tout = MTH2210.euler(lambda x,t : np.cos(t), x0, t0, tm, m)

print("x =", xout)
print("t =", tout)

En dimension n > 1 :

In [5]:
def f(x,t):
    return(np.array([np.cos(t),np.sin(t)]))
x0 = np.array([0,0])
(t0,tm) = (0, 2*np.pi)
m = 10

xout, tout = MTH2210.euler(f, x0, t0, tm, m, output="pipe")
# xout, tout = MTH2210.euler(f, x0, t0, tm, m)

print("x =", xout)
print("t =", tout)

   k ||            x_k             |    t_k   
----------------------------------------------
   0 || [+0.0000e+00, +0.0000e+00] |   +0.0000
   1 || [+6.2832e-01, +0.0000e+00] |   +0.6283
   2 || [+1.1366e+00, +3.6932e-01] |   +1.2566
   3 || [+1.3308e+00, +9.6688e-01] |   +1.8850
   4 || [+1.1366e+00, +1.5644e+00] |   +2.5133
   5 || [+6.2832e-01, +1.9338e+00] |   +3.1416
   6 || [+2.2204e-16, +1.9338e+00] |   +3.7699
   7 || [-5.0832e-01, +1.5644e+00] |   +4.3982
   8 || [-7.0248e-01, +9.6688e-01] |   +5.0265
   9 || [-5.0832e-01, +3.6932e-01] |   +5.6549
  10 || [+0.0000e+00, +0.0000e+00] |   +6.2832
Nombre maximal d'itérations k_max = 10 atteint

x = [array([0, 0]), array([0.62831853, 0.        ]), array([1.1366389 , 0.36931637]), array([1.3308   , 0.9668828]), array([1.1366389 , 1.56444923]), array([0.62831853, 1.9337656 ]), array([2.22044605e-16, 1.93376560e+00]), array([-0.50832037,  1.56444923]), array([-0.70248147,  0.9668828 ]), array([-0.50832037,  0.36931637]), array([0., 0

In [6]:
xout

[array([0, 0]),
 array([0.62831853, 0.        ]),
 array([1.1366389 , 0.36931637]),
 array([1.3308   , 0.9668828]),
 array([1.1366389 , 1.56444923]),
 array([0.62831853, 1.9337656 ]),
 array([2.22044605e-16, 1.93376560e+00]),
 array([-0.50832037,  1.56444923]),
 array([-0.70248147,  0.9668828 ]),
 array([-0.50832037,  0.36931637]),
 array([0., 0.])]

## Méthode d'approximation via RK4

In [ ]:
help("MTH2210.rk4")

En dimension 1 :

In [ ]:
def f(x,t):
    return(np.cos(t))
x0 = 0
(t0,tm) = (0, 2*np.pi)
m = 10

xout, tout = MTH2210.rk4(lambda x,t : np.cos(t), x0, t0, tm, m, output="pipe")
# xout, tout = MTH2210.rk4(lambda x,t : np.cos(t), x0, t0, tm, m)

print("x =", xout)
print("t =", tout)

En dimension n > 1 :

In [ ]:
def f(x,t):
    return(np.array([np.cos(t),np.sin(t)]))
x0 = np.array([0,0])
(t0,tm) = (0, 2*np.pi)
m = 10

xout, tout = MTH2210.rk4(f, x0, t0, tm, m, output="pipe")
# xout, tout = MTH2210.rk4(f, x0, t0, tm, m)

print("x =", xout)
print("t =", tout)